; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:portenta_h7_m7]
platform = ststm32
board = portenta_h7_m7
framework = arduino
build_src_filter = +<main.cpp> +<firmware/*.cpp>
lib_deps =
    sensirion/Sensirion I2C SCD4x@^1.1.0
    arduino-libraries/Arduino_PortentaMachineControl
    arduino-libraries/Arduino_Portenta_OTA@^1.2.1
monitor_speed = 115200
upload_protocol = dfu
board_upload.use_1200bps_touch = false
board_upload.wait_for_upload_port = false
board_upload.disable_flushing = true
extra_scripts = pre:disable_portenta_touch.py, post:make_ota.py
;upload_port = COM5
;monitor_port = COM5

[env:qspi_formatter]
platform = ststm32
board = portenta_h7_m7
framework = arduino
build_src_filter = +<qspi_formatter.cpp>
monitor_speed = 115200
upload_protocol = dfu
board_upload.use_1200bps_touch = false
board_upload.wait_for_upload_port = false
board_upload.disable_flushing = true
extra_scripts = pre:disable_portenta_touch.py

